# Generated by Django 2.2.4 on 2019-08-09 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=5)),
                ('etc', models.CharField(blank=True, default='', max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('class_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='accounts.Teacher')),
                ('students', models.ManyToManyField(related_name='classes', to='accounts.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('name', models.CharField(max_length=250)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='classes.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memo', to='classes.Class')),
            ],
        ),
    ]
