# Generated by Django 2.2.3 on 2019-08-07 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20190806_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='memo',
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('name', models.CharField(max_length=250)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='classes.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memo', to='classes.Class')),
            ],
        ),
    ]
