# Generated by Django 2.2.3 on 2019-08-08 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20190807_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='classes.Class'),
        ),
    ]
