# Generated by Django 2.2.3 on 2019-08-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20190808_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='content',
            field=models.CharField(max_length=250),
        ),
    ]
