# Generated by Django 2.2.3 on 2019-08-08 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20190808_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memo', to='classes.Class'),
        ),
    ]
