# Generated by Django 2.2.4 on 2019-08-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QandA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='TITLE')),
                ('content', models.TextField(null=True, verbose_name='CONTENT')),
                ('answer', models.CharField(blank=True, max_length=200, null=True, verbose_name='ANSWER')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create_date')),
                ('modify_date', models.DateField(auto_now=True, verbose_name='Modify_date')),
                ('answer_registered', models.CharField(default='답변대기', max_length=10)),
            ],
        ),
    ]
