# Generated by Django 2.2.3 on 2019-08-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='TITLE')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='DESCRIPTION')),
                ('content', models.TextField(null=True, verbose_name='CONTENT')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create_date')),
                ('modify_date', models.DateField(auto_now=True, verbose_name='Modify_date')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['-create_date'],
            },
        ),
    ]
